export const SAVE_BOOKING_ITEM = "SAVE_BOOKING_ITEM"
export const SAVE_BOOKING_FAIL = "SAVE_BOOKING_FAIL"
export const RESET_BOOKING_ITEM = "RESET_BOOKING_ITEM"

export const BOOKING_CREATE_REQUEST = "BOOKING_CREATE_REQUEST"
export const BOOKING_CREATE_SUCCESS = "BOOKING_CREATE_SUCCESS"
export const BOOKING_CREATE_FAIL = "BOOKING_CREATE_FAIL"
export const BOOKING_CREATE_RESET = "BOOKING_CREATE_RESET"

export const BOOKING_DETAILS_REQUEST = "BOOKING_DETAILS_REQUEST"
export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS"
export const BOOKING_DETAILS_FAIL = "BOOKING_DETAILS_FAIL"

export const BOOKING_LIST_REQUEST = "BOOKING_LIST_REQUEST"
export const BOOKING_LIST_SUCCESS = "BOOKING_LIST_SUCCESS"
export const BOOKING_LIST_FAIL = "BOOKING_LIST_FAIL"

export const BOOKING_DELETE_REQUEST = "BOOKING_DELETE_REQUEST"
export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS"
export const BOOKING_DELETE_FAIL = "BOOKING_DELETE_FAIL"

export const BOOKING_UPDATE_REQUEST = "BOOKING_UPDATE_REQUEST"
export const BOOKING_UPDATE_SUCCESS = "BOOKING_UPDATE_SUCCESS"
export const BOOKING_UPDATE_FAIL = "BOOKING_UPDATE_FAIL"
