export const CART_LIST_REQUEST = "CART_LIST_REQUEST"
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS"
export const CART_LIST_FAIL = "CART_LIST_FAIL"

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"

export const CART_LIST_RESET = "CART_LIST_RESET"
