export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_DESC_REQUEST = "PRODUCT_DESC_REQUEST"
export const PRODUCT_DESC_SUCCESS = "PRODUCT_DESC_SUCCESS"
export const PRODUCT_DESC_FAIL = "PRODUCT_DESC_FAIL"
