export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SHIPPING_ADDRESS_REQUEST = "USER_SHIPPING_ADDRESS_REQUEST"
export const USER_SHIPPING_ADDRESS_SUCCESS = "USER_SHIPPING_ADDRESS_SUCCESS"
export const USER_SHIPPING_ADDRESS_FAIL = "USER_SHIPPING_ADDRESS_FAIL"

export const USER_ADD_SHIPPING_ADDRESS_REQUEST =
	"USER_ADD_SHIPPING_ADDRESS_REQUEST"
export const USER_ADD_SHIPPING_ADDRESS_SUCCESS =
	"USER_ADD_SHIPPING_ADDRESS_SUCCESS"
export const USER_ADD_SHIPPING_ADDRESS_FAIL = "USER_ADD_SHIPPING_ADDRESS_FAIL"

